### ISSUE TITLE
Make fails despite guile being installed

### ISSUE THREAD

**Issue by 2bithacker** [plattfot/pinentry-rofi#1]
Tried to follow the install instructions, but the make command fails:

```
> make
Makefile:3: *** No guile support bailing out.  Stop.
```

I do have guile installed though:

```
> guile -v
guile (GNU Guile) 2.2.4
```

This is on Ubuntu 19.04.

**Comment by plattfot** [comment]
That's probably because Ubuntu's make isn't built with guile support. As the support for guile was added to make back in 2012 so doubt Ubuntu is using an ancient version of make.

I'll take a look at it tonight and see if I can workaround it.

**Comment by plattfot** [comment]
Did some testing and didn't notice any speed difference between running the script compiled or not compiled. And it's the compiling step that you're having issues with so removed that step. Let me know if that works for you or not.

**Comment by plattfot** [comment]
Haven't heard anything since June, assuming this is resolved. Please open it up again if that's not the case.
