### ISSUE TITLE
The latest version does not work

### ISSUE THREAD

**Issue by arkhan** [plattfot/pinentry-rofi#13]
Greetings, when updating to version 2.0.2 in Guix you get the following error, when executing pinentry-rofi:

![image](https://user-images.githubusercontent.com/3141865/106180525-668ee300-616a-11eb-9fc4-7408e449a80b.png)

Thanks

**Comment by plattfot** [comment]
I made some modifications to the search paths, so probably that's why it's broken. It works fine on my main machine running guix on Arch Linux. But I can reproduce this on my laptop running the same setup.

Are you running guix on a foreign distro or are you using Guix System?

**Comment by arkhan** [comment]
I'm running Guix System

**Comment by plattfot** [comment]
Ok, I think I fixed the issue. 
Do you mind testing this out on your end?
The fix is in the no-code-error branch:

```
git clone https://github.com/plattfot/pinentry-rofi.git
cd pinentry-rofi
git checkout no-code-error
guix package -f guix.scm
```

**Comment by plattfot** [comment]
I also figured out why my main machine was working, where as my laptop didn't. I had `guile` installed in the same profile as `pinentry-rofi` so the correct paths was exported to `pinentry-rofi`.

**Comment by arkhan** [comment]
Great thanks, with the latest update it works great
