### ISSUE TITLE
not building on arch linux

### ISSUE THREAD

**Issue by lumpsoid** [plattfot/pinentry-rofi#16]
tried to install using this git, but ran into path errors.
Installing `sudo pacman -S autoconf-archive` solved the errors.

Found on the AUR page: `2.0.3-1 could not be built in chroot, AX_COMPUTE_RELATIVE_PATHS seems to need autoconf-archive`.

**Comment by plattfot** [comment]
Hi,
Thanks for flagging this. I added `autoconf-archive` to `makedepends` so this should be resolved now.

Please reopen if that is not the case.
