### ISSUE TITLE
Run Rofi with configuration.

### ISSUE THREAD

**Issue by michael-burakov** [plattfot/pinentry-rofi#19]
Hi,

I want to launch `pinentry-rofi` with a custom theme, i.e. not the one specified in the default configuration path `~/.config/rofi/`. Can I provide a `theme` flag somehow? Thanks.

-Michael

**Comment by plattfot** [comment]
Hi,

Unfortunately passing flags to rofi right now isn't possible. Shouldn't be that hard to add though. I do not have any bandwidth to work on it this month but I can add that feature next month. If you want to work on that feature yourself I would gladly review and accept a PR.

I'm thinking it would be something along the line of `pinentry-rofi -- <rofi flags>`. I.e. use `--` then the rest that follows are just passed to `rofi`.

**Comment by plattfot** [comment]
Hi,
Sorry for the delay. I was on vacation.

I've created a PR (#20) that adds the option to pass options directly to rofi. Do you think you would be able to test it out and see if that works for you? With that you should be able to run `pinentry-rofi -- -config <config>` to change the config for example. Tested it locally with passing `-m 0`/`-m 1` to specify what monitor rofi should pop-up on and that worked.

**Comment by TheAifam5** [comment]
Thank you, @plattfot. I was actually searching for this possibility. I have merged the patch on my Gentoo setup and works fine.

**Comment by plattfot** [comment]
Awesome! @TheAifam5 thank you for testing and confirming it is working. I've now merged #20 and consider this issue resolved.  Please open it if that's not the case.
