### ISSUE TITLE
How to add options to gpg-agent.conf

### ISSUE THREAD

**Issue by ghost** [plattfot/pinentry-rofi#22]
Hello,

Maybe a dump question.
But how would I use the -- OPTIONS in my gpg-agent.conf
it works perfectly fine in the CLI with, for example: `echo GETPIN | /usr/bin/pinentry-rofi -- -m DP-3`
But as soon as I try to add something after, the binary (`pinentry-program /usr/bin/pinentry-rofi`) in my gpg-agent.conf the config doesn't work anymore.

**Comment by plattfot** [comment]
Hi,

Not a dumb question.  I assumed you could just attached the options after the command in `pinentry-program`.  But I just checked the source code for `gnupg` and it just expects the path to the pinentry program.  So best you can do right now is to wrap it up in a shell script. Something like this should work (note not tested):
```
#! /usr/bin/bash

/usr/bin/pinentry "$@" -- -m DP-3
```

And use that script as the `pinentry-program` in the gpg-agent.conf file

**Comment by ghost** [comment]
Nice. Thank you very much :)
That was easier than I thought. xD
Works perfectly fine :)
![Screenshot_2024-05-21-13-25-27_3840x1080
3840x2160
3840x2160](https://github.com/plattfot/pinentry-rofi/assets/55512972/38d3d3a1-8afc-4e89-a8d7-73b3664960c7)
